anonymize:
  seed:
    - firstname: Joseph
      lastname: Maxwell
      company: SwiftOtter, Inc.
      street: 123 Main Street
      city: Kansas City
      postcode: 66073
      phone: 202-555-0109
      ip: 240.36.159.75

    - firstname: Samina
      lastname: Cote
      street: 2475 Cinnamon Lane
      city: San Antonio
      postcode: 78201
      phone: 202-555-0156
      company: Superior Products
      ip: 181.226.219.191

    - firstname: Tina
      lastname: Wilde
      street: 3931 Jessie Street
      city: Arabia
      postcode: 45688
      phone: 202-555-0184
      company: SwipeWire
      ip: 78.223.172.48

    - firstname: Dillan
      lastname: Lucero
      street: 184 James Street
      city: New York
      postcode: 14450
      phone: 202-555-0135
      company: SecureSmarter
      ip: 203.54.176.154

    - firstname: Dominik
      lastname: Petty
      street: 4914 Goff Avenue
      city: Plainwell
      postcode: 49080
      phone: 202-555-0115
      company: Dwellsmith
      ip: 51.113.119.34

    - firstname: Reece
      lastname: Forbes
      street: 565 Sampson Street
      city: Albany
      postcode: 53502
      phone: 202-555-0190
      company: SalePush
      ip: 85.127.2.228

    - firstname: Susan
      lastname: Chadwick
      street: 1763 Davis Avenue
      city: Sacramento
      postcode: 95814
      phone: (244) 949-1729
      company: Cloudrevel
      ip: 147.199.158.244

    - firstname: Ahmed
      lastname: Macgregor
      street: 451 Wildwood Street
      city: Akron
      postcode: 43308
      phone: 907-555-0187
      company: Crowdstage, Inc.
      ip: 152.56.2.51

    - firstname: Lexi-Mae
      lastname: Barton
      street: 3180 Dancing Dove Lane
      city: New York
      postcode: 10004
      phone: 907-555-0192
      company: Acme Brands, Inc.
      ip: 53.243.127.225

    - firstname: Cassia
      lastname: Casteneda
      street: 2255 Red Maple Drive
      city: Alhambra
      postcode: 91801
      phone: 404-555-0175
      company: QuickSpace
      ip: 174.146.43.47

    - firstname: Robert
      lastname: Kramer
      street: 1367 Lowndes Hill Park Road
      city: Sherman Oaks
      postcode: 91403
      phone: 404-555-0162
      company: Rentoor, inc.
      ip: 173.8.26.43

    - firstname: Mercedes
      lastname: Montemayor
      street: 674 Cemetery Street
      city: Magnolia
      postcode: 61336
      phone: 307-555-0141
      company: Jumpsync Products, Inc.
      ip: 68.65.218.25

    - firstname: Paula
      lastname: Walker
      street: 3357 Zappia Drive
      city: Lexington
      postcode: 40507
      phone: 307-555-0126
      company: VisionSwipe, Inc.
      ip: 50.151.191.15

    - firstname: Beltane
      lastname: Lefèbvre
      street: 3477 Lake Floyd Circle
      city: Patuxent Naval Air Test c
      postcode: 20670
      phone: 307-555-0127
      company: Shipplier Supplies, Inc.
      ip: 87.172.86.188

    - firstname: Leilani
      lastname: Bishop
      street: 1445 Thompson Street
      city: Seal Beach
      postcode: 90740
      phone: 515-555-0164
      company: TechTack LLC
      ip: 213.56.195.24

    - firstname: Rufus
      lastname: Cervantes
      street: 1247 Heliport Loop
      city: Bloomington
      postcode: 47408
      phone: 515-555-0142
      company: Digimail For You, LLC
      ip: 124.9.254.185

    - firstname: Carole
      lastname: Barrow
      street: 2462 Pritchard Court
      city: Rio
      postcode: 26755
      phone: 515-555-0102
      company: Kaboom Fireworks
      ip: 194.59.122.241

    - firstname: Jaylen
      lastname: Meadows
      street: 1767 Stroop Hill Road
      city: Fort Wayne
      postcode: 46852
      phone: 860-555-0172
      company: Semicolon Bookstore
      ip: 68.162.14.52

    - firstname: Alfie-Jay
      lastname: Franco
      street: 4474 Brookview Drive
      city: San Jose
      postcode: 95113
      phone: 860-555-0178
      company: Bent Out of Shape Jewelry
      ip: 25.19.163.174

    - firstname: Jokubas
      lastname: Mccray
      company: Thank You Notes Express
      street: 720 Scenic Way
      city: Warrensburg
      postcode: 62573
      phone: 860-555-0131
      ip: 132.60.238.89

    - firstname: Carine
      lastname: Ricard
      street: 55, place de Miremond
      city: VILLENEUVE-SUR-LOT
      postcode: 47300
      company: 9Yards Media
      phone: 05.48.01.14.91
      ip: 38.28.94.247

    - firstname: Laurent
      lastname: Thibodeau
      street: 69, boulevard Aristide Briand
      city: Le Bouscat
      postcode: 33110
      company: Titan Alarm Group
      phone: 05.45.43.97.63
      ip: 87.122.192.251

    - firstname: Andrée
      lastname: Bienvenue
      street: 59, Avenue des Pr'es
      city: MONTIGNY-LÈS-METZ
      postcode: 57158
      phone: 03.31.34.92.91
      company: Pacific Alarm Group
      ip: 171.120.59.109

    - firstname: Eloïse
      lastname: Spijkers
      street: Verlengde Koolhoverweg 10
      city: Bocholtz
      postcode: 6351
      phone: 06-58223374
      company: Saga Builders
      ip: 249.230.160.198

    - firstname: Mirza
      lastname: Hulsen
      street: De Zaalsteden 70
      city: Gieten
      postcode: 9461
      phone: 06-40996488
      company: Drama Studio
      ip: 49.87.75.212

    - firstname: Michal
      lastname: Biarda
      street: 1004 Rabbit Str
      city: Lunapark
      postcode: 31415
      phone: 852-555-0129
      company: Hello World, Inc.
      ip: 197.45.92.201
